### ISSUE TITLE
Hyper extremely slow when reading data from remote storage compared to local SSD

### ISSUE THREAD

**Issue by djouallah** [tableau/hyper-db#56]
Hyper when using local ssd is literally the fastest SQL Engine these days, but the performance when reading from remote storage is extremely slow ?

I am using a notebook that leverage blobfusion to an azure storage account

```
for tbl in ['nation','region','customer','supplier','lineitem','orders','partsupp','part'] :
                dt = DeltaTable('/lakehouse/default/Tables/'+ tbl)
                delta = ['/lakehouse/default/Tables/' +tbl + "/" + i for i in dt.files()]
                print(tbl)
                connection.execute_list_query(f""" create temp EXTERNAL table IF NOT EXISTS {tbl} for array{delta} WITH ( FORMAT => 'parquet') """)
```

**Comment by vogelsgesang** [comment]
This might be due to sampling overhead. Hyper has to create a sample from your Iceberg file before it is able to process queries. Did you run the queries multiple times? This sampling overhead should only negatively impact the first query execution, since the sample is then cached for subsequent queries...

You can find a more detailed breakdown of query runtimes inside the `hyperd.log`. Look for events with `k` = `query-end`. Inside those events you will find a lot of fine-grained performance infos. If you are seeing large runtimes in the `pre-execution` phase, then this is almost certainly due to sample creation

**Comment by djouallah** [comment]
I am reading parquet files not iceberg, my issue is not sampling , but the queries are slow, is there a way to force Hyper to generate stats ?

**Comment by JFinis** [comment]
@djouallah I think your issue is that you are putting a high latency source (azure blob store) behind a file system interface. Hyper has two implementations for I/O: One for the local file system and one for Amazon S3. For S3, we assume high latency, so we do a lot prefetching and other optimizations to hide this high latency. For the local file system, we don't do that, as we expect a fast SSD where the latency is somewhat negligible.

Thus, Hyper is currently not good at reading from a local file system that has high latency. We could build a prefetching path for file systems with high latency, but this is non-trivial, as we use file system APIs here that are not async. We would need to switch our file system implementation to an async API like liburing, but as you can imagine, swapping out the file sytem API is no small task.

Thus, all in all, making file system fast for high latency backends would be a considerable amount of work on our side. Thus, I am actually quite sure that this will not happen in the near future, as local file systems are currently not our number one priority.

So, what can you do to mitigate the issue? I currently don't see a possibility TBH. We don't support Azure Blob Store directly, yet, so you cannot use the prefetching implementation we use for Amazon S3. Maybe we will support Azure Blob Store at some point in the future, but I can't guarantee that and there are also no definite timelines on this.

So your best bet is currently to either switch to Amazon S3 or download the files to an SSD first. I'm sorry I can't give you a satisfying answer, but that's the way it is right now.

**Comment by djouallah** [comment]
@JFinis thank you sir for the detailed answer.

**Comment by djouallah** [comment]
I have no idea what changed but using the latest update of Hyper fixed the problems, did you improved reading parquet with large row groups, anyway great job :)
